version: "3"
services:
  postgres:
    image: postgres:12-alpine 
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .docker.env
  adminer:
    image: adminer
    links:
      - postgres:postgres
    ports:
      - 8080:8080
volumes:
  pg_data:


